# server配置
server:
  port: 9002
  servlet:
    context-path: /

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rj221?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useInformationSchema=true&nullNamePatternMatchesAll=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.example.pojo
  global-config:
    db-config:
#      logic-delete-field: deleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      #table-prefix: news_ # 设置表的前缀

#jwt配置
jwt:
  token:
    tokenExpiration: 2000 #有效时间,单位分钟
    tokenSignKey: guojiye666!!!  #当前程序签名秘钥 自定义

